### PR TITLE
refactor: upgrade and rewrite

### PR DESCRIPTION
**Pull request by aoor9**
@Rabbitzzc Hello. Since last year this project has not been maintained. So, in this PR, I:

- upgraded dependencies to solve vulnerabilities 
- refactored all files in src folder to full Typescript, so classes are strictly typed and singularly importable
- fixed ESLint configuration after encountering some issues
- added Prettier to beautify code

Please review this ASAP

### CODE REVIEW

**Comment by Rabbitzzc** [comment]
ok. I will review in one week. Recently, I have been busy with work.

**Comment by Rabbitzzc** [comment]
In general, we recommend using one commit msg

**Comment by aoor9** [comment]
What does it mean? You want me to submit a new PR with only one commit?

**Comment by Rabbitzzc** [comment]
1.2.0 published.... It don't take the `static` method... but merged some configs.. Thanks

**Pull request merged**
